### ISSUE TITLE
Yarn.lock failed

### ISSUE THREAD

**Issue by Yarflam** [Yarflam/npm-dep-check#2]
## Expected Behavior

Scan a GIT project with `yarn.lock` to get a version of any NPM module.

## Current Behavior

Not found:

```
npm-dep-check . node-fetch
[yarn.lock]
undefined:1
{"

SyntaxError: Bad control character in string literal in JSON at position 2
    at JSON.parse (<anonymous>)
    at [...]\AppData\Roaming\nvm\v20.13.1\node_modules\npm-dep-check\index.js:51:29
    at Object.<anonymous> ([...]\AppData\Roaming\nvm\v20.13.1\node_modules\npm-dep-check\index.js:182:3)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.13.1
```

## Possible Implementation

Analysis is required to upgrade the module.

**Comment by Yarflam** [comment]
Upgrade the package to fix it!
